### ISSUE TITLE
Duda teórica con respecto a los ítemsets frecuentes

### ISSUE THREAD

**Issue by Geeermy** [IIC2433-2017-2/T01#11]
¡Hola!

Revisando el algoritmo Apriori, recuerdo que los ítemsets de un solo ítem también eran considerados frecuentes, a pesar de no poder obtener una regla de asociación a partir de ellos.

En FP-Growth no recuerdo que hiciéramos lo mismo. ¿Considero como ítemset frecuente los ítems individuales que cumplen con el umbral de soporte establecido? ¿O solo me quedo con los ítemsets de más de un ítem?

¡Gracias! =)

**Comment by bcsaldias** [comment]
Hola,

Si son itemset frecuentes, por definición. En la tarea solo se piden reglas
de asociación (que necesita al menos 2 ítems).

Para el calculo de las metricas debes conocer el soporte de los itemsets de
largo 1.

Saludos



El 24 sep. 2017 11:20, "Geeermy" <notifications@github.com> escribió:

¡Hola!

Revisando el algoritmo Apriori, recuerdo que los ítemsets de un solo ítem
también eran considerados frecuentes, a pesar de no poder obtener una regla
de asociación a partir de ellos.

En FP-Growth no recuerdo que hiciéramos lo mismo. ¿Considero como ítemset
frecuente los ítems individuales que cumplen con el umbral de soporte
establecido? ¿O solo me quedo con los ítemsets de más de un ítem?

¡Gracias! =)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/IIC2433-2017-2/T01/issues/11>, or mute the thread

**Comment by Hernan4444** [comment]
Colandome a la issue, entonces cuando piden la lista de itemset frecuentes, también ponemos los que tienen un solo ítem, aunque no los usemos para generar las reglas o esos los guardamos de forma internet pero al momento de retornar todos los itemset frecuentes, retornamos solo los de largo 2 o más?

Gracias!

**Comment by Geeermy** [comment]
¡Perfecto!

En todo caso, sí se piden ítemsets frecuentes:

> El atributo frequent itemsets, que retorna la lista de itemsets frecuentes ordenados por tamaño del set.

Entonces los pondré de todas formas :).

**Comment by bcsaldias** [comment]
Verdad!

Saludos

**Comment by bcsaldias** [comment]
Hola,

Los itemsets son sets de item, pueden ser de largo 1.

Saludos!
