### ISSUE TITLE
Duda con respecto al último paso de FP-Growth

### ISSUE THREAD

**Issue by Geeermy** [IIC2433-2017-2/T01#8]
¡Hola!

Estaba revisando mis apuntes y todavía no me queda muy clara la obtención de los itemsets frecuentes a partir del FP-Tree. En particular, cuando tomo dos ramas de la forma:

I2 --- I1 
I1 --- ...

¿Existirá alguna forma intuitiva de verlo? ¿o bien alguna referencia bibliográfica que pueda consultar sin problemas?

De antemano gracias :D

**Comment by jgmontoya** [comment]
Hola,

Según yo hay que tomar todas las posibilidades dentro de las ramas. Por cada una de estas posibilidades hay que chequear a ver si está contenido en las otras ramas y en ese caso sumar el soporte mínimo que corresponda.

Saludos

**Comment by vaopaso** [comment]
Hola, todavía no me queda claro esto. Según el algoritmo que hicimos en clase, si la suma de ramas resultante luego de haber hecho los caminos para el I3, me queda como: (Ejemplo ficticio)

        NULL
        /  \
     I1:3  I2:4
            |
           I1:2

Entonces los candidatos a combinarse con I3 quedarían de la forma:

     {I1:3}
     {I2:4 , I1:2}

Luego los itemsets freceuntes serían:

    {I1, I3} soporte: ??
    {I2, I3} soporte: 4
    {I2, I1, I3} soporte: min(4,2) = 2

¿Cuál sería el soporte del itemset {I1, I3}?

**Comment by jgmontoya** [comment]
Según entiendo el soporte de {I1, I3] sería 5 (3+2), la razón es que tienes en total 5 transacciones que involucran en conjunto al item I1 con el item I3.

Saludos!

**Comment by vaopaso** [comment]
Dale, gracias! Espero que sea así, porque en el ejemplo similar que hicimos en clases, en donde en una rama había {-- I1:2 } y en otra había  {-- I2:4 -- I1:2 }, el resultado final del itemset {I1,I3} era de soporte 2 (así lo había anotado yo, quizás me equivoqué), cuando según lo recién comentado debiera ser 2+2=4

**Comment by bcsaldias** [comment]
Hola a todos,

Gracias por responder :D

Si, es 4.

Creo que lo vimos como 4 en clases. Pero habían muchas cosas en la pizarra.
Eso pudo distraer.

Saludos!


El 22 sep. 2017 12:29, "vaopaso" <notifications@github.com> escribió:

Dale, gracias! Espero que sea así, porque en el ejemplo similar que hicimos
en clases, en donde en una rama había {-- I1:2 } y en otra había {-- I2:4
-- I1:2 }, el resultado final del itemset {I1,I3} era de soporte 2 (así lo
había anotado yo, quizás me equivoqué), cuando según lo recién comentado
debiera ser 2+2=4

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/IIC2433-2017-2/T01/issues/8#issuecomment-331479861>,
or mute
the thread

**Comment by vaopaso** [comment]
Tengo otra duda. Siguiendo un ejemplo similar al anterior, ¿qué pasa si el caso es de la siguiente manera?:

       NULL
          \
          I2:4
          /  \
       I1:2  I4:3

¿Cómo serían los candidatos a combinarse con I3? ¿Y luego los itemsets frecuentes?

**Comment by bcsaldias** [comment]
Hola,

Ese árbol no es válido: 4 != 2 + 3

Saludos

El 22 sep. 2017 17:51, "vaopaso" <notifications@github.com> escribió:

Tengo otra duda. Siguiendo un ejemplo similar al anterior, ¿qué pasa si el
caso es de la siguiente manera?:

   NULL
      \
      I2:4
      /  \
   I1:2  I4:3

¿Cómo serían los candidatos a combinarse con I3? ¿Y luego los itemsets
frecuentes?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/IIC2433-2017-2/T01/issues/8#issuecomment-331557361>,
or mute
the thread

**Comment by vaopaso** [comment]
Bueno, pongo un mejor ejemplo: Si tuviera que combinar con I5 y la suma de nivel me da lo siguiente:

       NULL
        |
       I2:2
       /  \
    I3:1  I1:1
     |
    I1:1

Suponiendo que el soporte minimo es 1 (y por ende este arbol no se poda):
¿Cómo serían los candidatos a combinarse con I5? ¿Y luego los itemsets frecuentes?

**Comment by jgmontoya** [comment]
Hola,
Según entiendo tendrías como candidatos a todas las combinaciones posibles de esos elementos, lo que te generaría los siguientes itemsets frecuentes:
  * {I1, I5}: 2
  * {I2, I5}: 2
  * {I3, I5}: 1
  * {I1, I2, I5}: 2
  * {I1, I3, I5}: 1
  * {I2, I3, i5}: 1

Saludos!

**Comment by Geeermy** [comment]
@jgmontoya  Me parece que te faltó este caso:

* {I2, I3, I1, I5}: 1

¿O me equivoco?

**Comment by jgmontoya** [comment]
Jajaja si, ese también va :upside_down_face:
